
import React from 'react';
// Corrected import to use HistoryItem which is defined in types.ts
import { HistoryItem } from '../types';

interface AnalysisDisplayProps {
  analysis: HistoryItem;
  imageUrl?: string;
}

const AnalysisDisplay: React.FC<AnalysisDisplayProps> = ({ analysis, imageUrl }) => {
  const severityColors = {
    Low: 'bg-yellow-100 text-yellow-700',
    Medium: 'bg-orange-100 text-orange-700',
    High: 'bg-red-100 text-red-700',
  };

  const downloadReport = () => {
    // Added fallbacks for optional fields in HistoryItem
    const reportContent = `
FLORAGUARD AI - PLANT HEALTH REPORT
Generated on: ${new Date(analysis.timestamp).toLocaleString()}
--------------------------------------------------

PLANT: ${analysis.plantName}
IDENTIFICATION: ${analysis.diseaseName || 'N/A'}
SEVERITY: ${analysis.severity || 'N/A'}

SYMPTOMS & SIGNS:
${(analysis.symptoms || []).map(s => `- ${s}`).join('\n')}

TREATMENT - ORGANIC SOLUTIONS:
${(analysis.cures?.organic || []).map(c => `- ${c}`).join('\n')}

TREATMENT - CHEMICAL/PESTICIDE SOLUTIONS:
${(analysis.cures?.chemical || []).map(c => `- ${c}`).join('\n')}

PREVENTION MEASURES:
${(analysis.prevention || []).map(p => `- ${p}`).join('\n')}

--------------------------------------------------
This report was generated by FloraGuard AI Assistant.
Always consult with a local agricultural extension officer for regional-specific advice.
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `FloraGuard_Report_${analysis.plantName.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const getPurchaseUrl = (chemical: string) => {
    // Attempt to find the link provided by AI
    const pLink = analysis.purchaseLinks?.find(l => 
      l.pesticideName.toLowerCase().includes(chemical.toLowerCase()) || 
      chemical.toLowerCase().includes(l.pesticideName.toLowerCase())
    );
    
    // If AI provided a link, use it. Otherwise, create a guaranteed fallback link.
    if (pLink?.url) return pLink.url;
    
    // Fallback: Google Shopping search link
    return `https://www.google.com/search?tbm=shop&q=${encodeURIComponent(chemical + ' pesticide for ' + analysis.plantName)}`;
  };

  return (
    <div className="bg-white rounded-2xl shadow-lg overflow-hidden border border-slate-100 animate-in fade-in slide-in-from-bottom-4 duration-500 flex flex-col">
      {/* Top: User Uploaded Image */}
      {imageUrl && (
        <div className="w-full h-[300px] md:h-[400px] relative">
          <img 
            src={`data:image/jpeg;base64,${imageUrl}`} 
            alt="Analyzed Plant Leaf" 
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent"></div>
          <div className="absolute bottom-6 left-6 right-6 flex items-end justify-between">
            <div className="text-white">
              <h2 className="text-xs font-bold uppercase tracking-widest text-emerald-300 mb-1">{analysis.plantName}</h2>
              <h1 className="text-3xl font-black leading-tight">{analysis.diseaseName || 'Disease Identification'}</h1>
            </div>
            {/* Added safety check for severity colors mapping */}
            <div className={`px-4 py-1.5 rounded-full text-xs font-bold uppercase tracking-wider shadow-lg ${severityColors[analysis.severity as keyof typeof severityColors] || 'bg-slate-100 text-slate-700'}`}>
              {analysis.severity || 'Unknown'} Severity
            </div>
          </div>
        </div>
      )}

      {/* Bottom: Analysis Results */}
      <div className="p-8 space-y-8">
        <div className="flex flex-wrap gap-4 justify-between items-center border-b border-slate-100 pb-4">
          <h3 className="text-lg font-bold text-slate-800">Health Analysis Details</h3>
          <button 
            onClick={downloadReport}
            className="px-4 py-2 text-emerald-600 hover:bg-emerald-50 rounded-xl transition-all border border-emerald-100 flex items-center space-x-2 text-sm font-bold shadow-sm"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a2 2 0 002 2h12a2 2 0 002-2v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            <span>Download Report</span>
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <section>
            <h3 className="flex items-center text-sm font-black text-slate-900 mb-4 uppercase tracking-tighter">
              <span className="w-8 h-8 rounded-lg bg-emerald-100 flex items-center justify-center mr-3">🔍</span>
              Symptoms & Signs
            </h3>
            <ul className="space-y-3">
              {(analysis.symptoms || []).map((s, i) => (
                <li key={i} className="text-sm text-slate-600 flex items-start bg-slate-50 p-3 rounded-xl border border-slate-100">
                  <span className="text-emerald-500 font-bold mr-3 mt-0.5">●</span> {s}
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h3 className="flex items-center text-sm font-black text-slate-900 mb-4 uppercase tracking-tighter">
              <span className="w-8 h-8 rounded-lg bg-emerald-100 flex items-center justify-center mr-3">🛡️</span>
              Prevention Guide
            </h3>
            <ul className="space-y-3">
              {(analysis.prevention || []).map((p, i) => (
                <li key={i} className="text-sm text-slate-600 flex items-start bg-emerald-50/30 p-3 rounded-xl border border-emerald-100/50">
                  <span className="text-emerald-500 font-bold mr-3 mt-0.5">✓</span> {p}
                </li>
              ))}
            </ul>
          </section>
        </div>

        <div className="bg-slate-900 rounded-2xl p-6 text-white shadow-xl">
          <h3 className="text-xs font-black text-emerald-400 mb-6 uppercase tracking-[0.2em]">Treatment & Pest Control</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-8">
            <div>
              <p className="text-sm font-bold text-slate-200 mb-3 flex items-center">
                <span className="mr-2">🍃</span> Organic & Natural
              </p>
              <div className="flex flex-wrap gap-2">
                {(analysis.cures?.organic || []).map((c, i) => (
                  <span key={i} className="px-3 py-1.5 bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-xs font-medium rounded-lg">{c}</span>
                ))}
              </div>
            </div>
            <div>
              <p className="text-sm font-bold text-slate-200 mb-3 flex items-center">
                <span className="mr-2">🧪</span> Chemical Pesticides
              </p>
              <div className="flex flex-col gap-3">
                {(analysis.cures?.chemical || []).map((c, i) => (
                  <div key={i} className="flex items-center justify-between bg-white/5 border border-white/10 rounded-xl p-3">
                    <span className="text-xs font-medium text-slate-300 pr-2">{c}</span>
                    <a 
                      href={getPurchaseUrl(c)} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="flex items-center space-x-1.5 px-3 py-1 bg-emerald-500 hover:bg-emerald-600 text-white text-[10px] font-bold uppercase tracking-wider rounded-lg transition-colors shadow-sm flex-shrink-0"
                    >
                      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                      </svg>
                      <span>Buy Now</span>
                    </a>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AnalysisDisplay;
